str = "Hello World!"
print(str.endswith("Hell"))
print(str.startswith("!"))
print(str.upper())
print(str.lower())
print(str.capitalize())
print(str.title())
print(str.count("Hello"))
print(str.find("Hello"))
print(str.replace("Hello", "World"))
print(str.split("l"))
print(str.rsplit("l"))
print(str.partition("l"))
print(str.rpartition("l"))
print(str.isupper())
print(str.islower())
print(str.istitle())
print(str.isspace())
print(str.isdigit())
print(str.isnumeric())
print(str.isalnum())
print(str.isalpha())
print(str.swapcase())
print(str.strip())
print(str.lstrip())
print(str.rstrip())